trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Test Replace
  displayName: Test Replace
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
      steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              git config --global user.email "mihai.sava@endava.com"
              git config --global user.name "Mihai Sava"
              git remote set-url origin https://TheDevOpsPlayGround@dev.azure.com/TheDevOpsPlayGround/ArgoCD/_git/GitOPS
              git checkout -B main