apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoappnetcore
  labels:
    app: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      service: todoappnetcore
  template:
    metadata:
      labels:
        app: todo-app
        service: todoappnetcore
    spec:
      containers:
        - name: todoappnetcore
          image: docker.io/masaru2604/dotnetcoresqldb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5000
            - name: WebApiBaseAddress
              value: http://todo
            - name: ASPNETCORE_ENVIRONMENT
              value: Prod
---
apiVersion: v1
kind: Service
metadata:
  name: todoappnetcore
  labels:
    app: todo-app
    service: todoappnetcore
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    service: todoappnetcore